### concatenate 메소드, 배열 합치기

- concatenate 메소드는 선택한 축 (axis)의 방향으로 배열을 연결해주는 메소드

#### 1차원 배열

In [2]:
import numpy as np

a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])
print(a1)
print(b1)

[1 2 3]
[4 5 6]


In [4]:
#1차원 배열에 concanate 적용하기

np.concatenate((a1, b1), axis=0)

array([1, 2, 3, 4, 5, 6])

- 1차원에서 axis=0은 행방향이나 열방향이라는 개념이 없음


- axis=1로 하면 에러 발생 >> 방향이 axis=0 하나 뿐이기 때문(직선이라고 생각)

#### 2차원 배열

In [5]:
a2 = np.array([ [1, 2, 3], [10, 20, 30] ])
b2 = np.array([ [4, 5, 6], [40, 50, 60] ])
print(a2)
print(b2)

[[ 1  2  3]
 [10 20 30]]
[[ 4  5  6]
 [40 50 60]]


In [6]:
#2차원 배열에서 axis=0은 행방향(위>아래)을 의미
np.concatenate((a2, b2), axis=0)

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [40, 50, 60]])

In [7]:
#열방향(왼>오)
np.concatenate((a2, b2), axis=1)

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

#### 3차원 배열